version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: projeto-filmes-app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: projeto-filmes-nginx
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: projeto-filmes-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filmes
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: projeto-filmes-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - app

volumes:
  dbdata:
